- .travis.yml
- rest_framework_gis/serializers.py
This commit adds Python 2.6 and 3.x compatibility.
As discussed in pull #34, I am recreating this pull request with 2 clean commits. As before, all tests are passing.
> Drf 3.0: Python 2.6 and 3.x Compatibility

- rest_framework_gis/serializers.py
- tests/django_restframework_gis_tests/tests.py
I also stumbled about the problem mentioned in issue #51 that the GeoFeatureModelSerializer is not able to deserialize request which only contain a partial representation of the model without the geometry field. When no geometry is provided the serializer will currently raise a KeyError. This issue is crucial to support for example partial PATCH requests.
This pull request fixes #51 and also adds unittests for the expected behavior.
> Support partial modifications without geometries when using the GeoFeatureModelSerializer. Fixes issue #51

- requirements-test.txt
- rest_framework_gis/serializers.py
- tests/django_restframework_gis_tests/models.py
- tests/django_restframework_gis_tests/serializers.py
- tests/django_restframework_gis_tests/tests.py
- tests/django_restframework_gis_tests/urls.py
- tests/django_restframework_gis_tests/views.py
This is a really subtle weird error, but I was getting errors serializing an optional ImageField with no file associated with it--the errors kept insisting that there ought to be a file. I tried adding `allow_empty_file=True` and that works fine for GeoModelSerializer and the regular DRF ModelSerializer, but broke with GeoFeatureModelSerializer.
It turns out, in the GeoFeatureModelSerializer code, if I check _explicitly_ for whether the value is `None`, I can get GeoFeatureModelSerializer to work. My hunch is that ImageField, when empty, is a value that is equal to `None` (i.e. `<ImageFieldFile: None>`), but will not pass a merely "falsey" condition.  So I had to write it as;
`if value is not None:`
rather than
`if value:`
This is actually what DRF ModelSerializer itself does, more or …
> check explicitly for not None on field values

- README.rst
- rest_framework_gis/fields.py
- tests/django_restframework_gis_tests/serializers.py
- tests/django_restframework_gis_tests/tests.py
- tests/django_restframework_gis_tests/urls.py
- tests/django_restframework_gis_tests/views.py
According to geojson spec `geometry` field may have `null` value
http://geojson.org/geojson-spec.html#geojson-objects
>A GeoJSON object with the type "Feature" is a feature object.
>A feature object must have a member with the name "geometry". The value of the geometry member is a geometry object as defined above or a JSON null value.
Corresponding Python value in the PR is set to be `None`, and it is allowed to be passed as value for `geo_field` from a serializer.
> allow None value for geometry

- rest_framework_gis/serializers.py
If one of instance fields has a value of `False` or `''` (empty string) the serializer would translate those values to `None` which would in turn become `null` in json. This PR preserves correct field values.
> fixed False or empty string values

- rest_framework_gis/fields.py
- tests/django_restframework_gis_tests/tests.py
Return GEOSGeometry instead of geojson property of GEOSGeometry to_internal_value() method of GeometryField.
Fixes https://github.com/djangonauts/django-rest-framework-gis/issues/74
> Return GEOSGeometry instead of geojson property

- rest_framework_gis/serializers.py
- tests/django_restframework_gis_tests/models.py
- tests/django_restframework_gis_tests/serializers.py
- tests/django_restframework_gis_tests/tests.py
The current implementation fails to serialize properties holding the value None. This may not affect al types of field as it depends how the field handles its conversion in its Field.to_representation() method. At least with datetime fields the attempt to serialize a None value will result in an AttributeError -- see the following stacktrace:
[...]
File "/home/nico/environments/venv-django17/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 466, in data
ret = super(Serializer, self).data
File "/home/nico/environments/venv-django17/local/lib/python2.7/site-packages/rest_framework/serializers.py", line 213, in data
self._data = self.to_representation(self.instance)
File "/home/nico/environments/venv-django17/local/lib/python2.7/site-packages/rest_framework/serializers.py …
> Fix serialization of properties holding None values

- tests/django_restframework_gis_tests/test_filters.py
Those tests fail because of missing features in spatialite.
> Skip some tests if spatialite DB backend is active.

- MANIFEST.in
This adds `CHANGES.rst` and `runtests.py` to the source tarball to make the pypi tarball usable for Debian packaging. It also cleans up the entries in MANIFEST.in for better readability, refines the `recursive-include`for tests and removes the `recursive-excludes` entry as it should not have any effect on the resulting tarball (only explicit includes present).
> Include assets in source tarball

- README.rst
The Django docs gives the following warning for `JSONField` (should be valid for `HStoreField` as well):
> If you give the field a default, ensure it’s a callable such as dict (for an empty default) or a callable that returns a dict (such as a function). Incorrectly using default={} creates a mutable default that is shared between all instances of JSONField.
Fixes #107.
> README: fix example

- README.rst
- requirements-test.txt
- tests/django_restframework_gis_tests/views.py
Fixes https://github.com/djangonauts/django-rest-framework-gis/issues/120.
> Fix tests for django-filter 1.0.0

- README.rst
Hi! I think I found a typo in the order of the params in "in_bbox" param. When integrating the plugin, I found that it only works if the order is lon, lat (instead of lat, lon). I've also looked at the code and I think that the proper order is lon, lat.
Thank you very much for your plugin!! Very simple to use and very well documented ^_^
> Corrected wrong bounding box params in README

- .travis.yml
- README.rst
- tox.ini
This is rudimentary, but makes it a lot easier to run the tests.
Please consider adopting it and mention it in the docs.
It could also be used on Travis.
> [RFC] add tox.ini / support for pytest

- tests/django_restframework_gis_tests/test_performance.py
The test_geojson_performance test was failing an assertion in DRF>=3.5   Fixed by adding fields='__all__' to the PerfSerializer class.
> Fixes for test_geojson_performance with DRF >=3.5

- requirements-test.txt
- requirements.txt
- rest_framework_gis/fields.py
- tests/django_restframework_gis_tests/tests.py
Fixes #126 
We have a project that has a need to support GeometryCollection fields.  After poking around I decided to try altering the GeometryField and GeometrySerializerMethodField to use GeoDjango's built-in geojson output instead of creating a GeoJSON object on the fly.  It seems to be a small change and fixes the issue in our project without breaking elsewhere.
> Add support for GeometryCollection fields

- requirements-test.txt
This change didn't seem to cause any issues in Travis testing.
Do we want to cap it at 1.1.0 or allow it to go up as django-filter is updated?
Fixes #148.
> [QA] Change django-filter test requirement to latest

- rest_framework_gis/filters.py
Using `forms.BaseGeometryWidget` will cause a IsADirectoryError, because
of an empty template_name being used.
This was added by me in eb54fc0.
This patch changes it to use a simple TextInput; I can imagine using a
nicer widget here, but that requires to also add/handle the required
media assets, which was not trivial (IIRC).
```
Template error:
In template …/project/.venv/lib/python3.6/site-packages/django_filters/templates/django_filters/rest_framework/form.html, error at line 4
21
1 : {% load i18n %}
2 : <h2>{% trans "Field filters" %}</h2>
3 : <form class="form" action="" method="get">
4 :      {{ filter.form.as_p }}
5 :     <button type="submit" class="btn btn-primary">{% trans "Submit" %}</button>
6 : </form>
7 :
Traceback:
File "…/Vcs/django/django/core/handlers/exception.py" in …
```
> Fix default widget for GeometryFilter

- README.rst
- rest_framework_gis/fields.py
- tests/django_restframework_gis_tests/test_fields.py
This is a continuation of #158 (I rebased the branch, making the PR ineligible for re-opening).
This is a feature proposal for adding flags to the `GeometryField` to reduce the precision of a geometry.  Perhaps the geometry is stored in high precision in the database, but for the sake of reducing response-size it may make sense to round the coordinates to a certain level.
This features has two portions:
1. Rounding all coordinates to a specified precision.
2. Removing redundant coordinates.  When coordinates get rounded, it's more likely that there will be redundant values. Consider rounding `[ (1.1001, 1.2302), (1.1201, 1.2203), (1.1103, 1.240) ]` to a precision value of `1`, the resultant array would be `[ (1.1, 1.2), (1.1, 1.2), (1.1, 1.2)]`. For the sake of size, it may as well be …
> Flag to reduce precision of GeometryField

- requirements-test.txt
- requirements.txt
- rest_framework_gis/fields.py
Hello. Django vendors `six`, so it's not necessary to include it as an additional dependency.
> Use Django's vendored 'six'

- .travis.yml
- Dockerfile
- docker-compose.yml
- requirements-test.txt
- requirements.txt
- tests/django_restframework_gis_tests/tests.py
- tests/django_restframework_gis_tests/views.py
- tox.ini
- Added python 3.7 to travis and tox
- removed python2  from travis and tox
- Had to update postgres for travis to 9.4 and postgis to 2.4 because django 2.1 dropped support for 9.3
also fixes #170 
Fails on python 2. Looks like I need to fix #171 as well. Can someone guide me so that I can drop python 2 support. What should be done I see multiple comments like 
```
class GeoJsonDict(OrderedDict):
"""
Used for serializing GIS values to GeoJSON values
TODO: remove this when support for python 2.6/2.7 will be dropped
"""
```
Should `GeoJsonDict` be removed?
> Support django 2.1, DRF 3.9 and use django-filters > 2.0

- setup.py
I've created this PR to show the README and useful links in the PyPi packages page, removing the message "The author of this package has not provided a project description":
https://pypi.org/project/djangorestframework-gis/
> Added long description and additional urls in setup module

- README.rst
After last release the README is visible in on pypi.org but as raw code.
https://pypi.org/project/djangorestframework-gis/
I checked the README.rst file and found this error:
```bash
$ python setup.py check -r -s
running check
warning: check: Error in "code-block" directive:
maximum 1 argument(s) allowed, 7 supplied. (line 663)
error: Please correct your package.
```
I fixed the README.rst and checked again to confirm it's validity.
For the next release could be useful check the package before submit it:
https://packaging.python.org/guides/making-a-pypi-friendly-readme/#validating-restructuredtext-markup
> Fixed README invalid markup that cause PyPI to show the raw source.

- README.rst
The sentence can be misunderstood easily as it does not elaborate that
GeoModelSerializer does not need to be implemented if you're using
ver 0.9.3.
It misleads the user into thinking that it has been deprecated for good.
Closes https://github.com/djangonauts/django-rest-framework-gis/issues/156
> README.rst: Comprehendable deprecation warning.

- rest_framework_gis/fields.py
Django 3 has now removed the six util module but this package already seems to only support higher than Python 3.4 as of version 0.14.x.
> Removed six dependency

- rest_framework_gis/serializers.py
Update the way that `to_representation` removes already processed fields, as per #194.
> fix compatibility issues w/ DRF 3.10

- Dockerfile
- docker-compose.yml
- tests/settings.py
This PR should fix the docker build.
- Adds `--no-cache` for Alpine repo installs
- Adds `--no-cache-dir` to install test requirements
- Adds `README.rst` to compose volumes to fix runtime errors
> Fix docker build

- .travis.yml
- requirements-test.txt
- tox.ini
According to [the official docs](https://github.com/coveralls-clients/coveralls-python/blob/master/docs/usage/tox.rst), coveralls and coverage should have been run in tox, so coverage can collect the test data. Also remove coverage dependency because coveralls already has a dependency on coverage. Minor fix to tox.ini included so coverage can run properly.
I add `travis` as env to prevent coveralls run on local tox test, and add `-` in before `coveralls` call to ignore the exit code because build is considered success even though coveralls failed (in respect to other repos that calls `coveralls` in `after_success`)
> [ci] Fix coveralls

- rest_framework_gis/fields.py
- tests/django_restframework_gis_tests/tests.py
Fixed GeometryField exception when containing an empty Point geometry
Fixes #168
> [bug] Fixed GeometryField exception #168

- README.rst
There is a small typo in README.rst.
Should read `equivalent` rather than `equivalant`.
> docs: Fix simple typo, equivalant -> equivalent

- requirements-test.txt
- rest_framework_gis/schema.py
- tests/django_restframework_gis_tests/serializers.py
- tests/django_restframework_gis_tests/test_schema_generation.py
- tests/django_restframework_gis_tests/views.py
The intial implementation of schema generation only supported
serializers which subclassed GeoFeatureModel*Serializer. This meant that
models which have standalone GeometryFields would not properly generate
a schema. This change adds support for that use case.
Fixes #257
> Add schema generation support for plain GeometryFields

- rest_framework_gis/serializers.py
- tests/django_restframework_gis_tests/serializers.py
- tests/django_restframework_gis_tests/tests.py
- tests/django_restframework_gis_tests/urls.py
- tests/django_restframework_gis_tests/views.py
When serializing a model, the value of its `id_field` is written in the `id` attribute
of the GeoJSON feature.
This behaviour is however not mirrored by the deserialization logic: deserializing a
model through GeoFeatureModelSerializer ignores the `id` field set in the given GeoJSON
feature.
This commit solves this issue by mirroring the serialization logic:
- When deserializing a model, the `id` attribute of the GeoJSON feature is written as the
`id_field` of the django model.
Fixes #272
> [fix] Deserialize id_field #272

- .github/workflows/ci.yml
- rest_framework_gis/filters.py
- tests/django_restframework_gis_tests/views.py
- tests/settings.py
- tox.ini
The test `tests.django_restframework_gis_tests.test_filters.TestRestFrameworkGisFilters.test_GeometryField_filtering` was failing. After checking my database logs, it seemed that postgres was not receiving the right query, as the where clause was missing.
I looked a bit into the django-filter setup and it needed an update.  
The fix was to rename the attribute `filter_class` to `filterset_class`, as per [the doc](https://django-filter.readthedocs.io/en/stable/guide/rest_framework.html#adding-a-filterset-with-filterset-class).
> Fix : django-filter looks for 'filterset_class' attribute now

- .github/workflows/ci.yml
- README.rst
- rest_framework_gis/__init__.py
- rest_framework_gis/filters.py
- tests/django_restframework_gis_tests/admin.py
- tests/django_restframework_gis_tests/test_bbox.py
- tests/django_restframework_gis_tests/test_filters.py
- tests/django_restframework_gis_tests/tests.py
- tox.ini
Closes #312
* Removes any compatibility code or doc for <4.2 versions of Django
* Remove 3.2 from CI and docs
* Modernize the code for Django 4.2 with the help of django-upgrade
> Remove Django 3.2 support

- tests/django_restframework_gis_tests/test_filters.py
- tests/django_restframework_gis_tests/tests.py
The main branch had two small issues with unused imports that causes CI to fail.
> Remove unused imports

- tox.ini
Refers to 
- https://github.com/openwisp/django-rest-framework-gis/issues/314
- https://github.com/openwisp/django-rest-framework-gis/pull/317
I missed the 3.8 related config in tox file in https://github.com/openwisp/django-rest-framework-gis/pull/317
> [cleanup] Remove Python 3.8 env from tox

- rest_framework_gis/apps.py
- tests/django_restframework_gis_tests/tests.py
- tox.ini
Closes #320 .
* Remove unused DRF environments from tox config
* Remove compatibility code for unsupported DRF versions
> [cleanup] Drop support for untested DRF versions

- .github/workflows/version-branch.yml
- CHANGES.rst
- requirements-test.txt
- rest_framework_gis/__init__.py
> [ci] Added GitHub workflow to replicate commits to version branch
